"""branch 纯 Python 公开 API。

本包聚合不可变分支模型、严格配置解析、svn:externals 解析/重写、只读前置校验、
BranchPlan 和规范 codec。导入本包只加载类型与纯函数，不访问 SVN、文件系统或秘密
服务；真正的复制与 apply 能力仍留给后续计划和受控管理端口。
"""

from branch.config import (
    BranchConfig,
    BranchConfigError,
    MappingRule,
    load_branch_config,
    load_config,
    normalize_branch_config,
    parse_branch_config,
)
from branch.externals import (
    External,
    ExternalClosureReport,
    ExternalDocument,
    ExternalEntry,
    ExternalLine,
    ExternalParseError,
    ExternalRewriteChange,
    ExternalRewriteError,
    ExternalRewritePlan,
    ExternalRewriteResult,
    ExternalRewriteRule,
    ExternalSyntax,
    parse_externals,
    render_externals,
    rewrite_external_plan,
    rewrite_externals,
)
from branch.model import (
    BranchCopy,
    BranchResult,
    BranchSource,
    BranchStatus,
    BranchTarget,
    BranchValidationError,
    PropertyChange,
)
from branch.validator import (
    BranchPreconditionError,
    BranchPreconditionValidator,
    BranchRepositorySnapshot,
    ExternalPropertySummary,
    NodeKind,
    ReadOnlySourceProvider,
    RepositoryNodeSnapshot,
    RepositoryNodeType,
    RepositorySnapshot,
    SourceProvider,
    ValidatedBranchSnapshot,
)
from branch.planner import (
    BranchPlan,
    BranchPlanError,
    BranchPlanner,
    compute_plan_id,
    plan_payload_without_id,
)
from branch.codec import BranchPlanCodec, BranchPlanCodecError, BranchPlanFactory

__all__ = [
    "BranchConfig",
    "BranchConfigError",
    "MappingRule",
    "load_branch_config",
    "load_config",
    "normalize_branch_config",
    "parse_branch_config",
    "External",
    "ExternalClosureReport",
    "ExternalDocument",
    "ExternalEntry",
    "ExternalLine",
    "ExternalParseError",
    "ExternalRewriteChange",
    "ExternalRewriteError",
    "ExternalRewritePlan",
    "ExternalRewriteResult",
    "ExternalRewriteRule",
    "ExternalSyntax",
    "parse_externals",
    "render_externals",
    "rewrite_external_plan",
    "rewrite_externals",
    "BranchCopy",
    "BranchResult",
    "BranchSource",
    "BranchStatus",
    "BranchTarget",
    "BranchValidationError",
    "PropertyChange",
    "BranchPreconditionError",
    "BranchPreconditionValidator",
    "BranchRepositorySnapshot",
    "ExternalPropertySummary",
    "NodeKind",
    "ReadOnlySourceProvider",
    "RepositoryNodeSnapshot",
    "RepositoryNodeType",
    "RepositorySnapshot",
    "SourceProvider",
    "ValidatedBranchSnapshot",
    "BranchPlan",
    "BranchPlanError",
    "BranchPlanner",
    "compute_plan_id",
    "plan_payload_without_id",
    "BranchPlanCodec",
    "BranchPlanCodecError",
    "BranchPlanFactory",
]
